<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="targetNamespace=company"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="usuarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[\w.]{6,30}@\w+\.\w+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}[-\s]\d{3}[-\s]\d{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="codigoPostal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{5}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombreUsuario">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\w{3,15}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="contrasena">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value=".{6,20}"/>
                                    </xs:restriction>
                                </xs:simpleType>  
                            </xs:element> 
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>